"""
Copyright 2016 Michael Spiegel, Wilhelm Kleiminger

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import shutil
import unittest
import atexit, os
from smart_heating_local.config import Config

class ConfigTestCase(unittest.TestCase):

    TEMP_DIR = 'temp'
    CONFIG_PATH = TEMP_DIR + '/test_config'

    def setUp(self):
        # Create temporary directory for config files
        if not os.path.exists(self.TEMP_DIR):
            os.mkdir(self.TEMP_DIR)
        Config.CONFIG_PATH = self.CONFIG_PATH

    def tearDown(self):
        # Remove shelve files generated by config
        shutil.rmtree(self.TEMP_DIR)

    def test_thermostat_macs(self):
        macs = ['22:22:22:22:33:33:33:33', '11:11:11:11:44:44:44:44']
        Config().save_thermostat_macs(macs)

        self.assertEqual(macs, Config().get_thermostat_macs())

    def test_heating_table(self):
        mac = '22:22:22:22:33:33:33:33'
        heating_table_entries = [{'id': 1, 'url': 'dummy'},
                          {'id': 2, 'url': 'stub'}]

        Config().save_heating_table(mac, heating_table_entries)

        self.assertEqual(heating_table_entries, Config().get_heating_table(mac))
