import shutil
import unittest
import atexit, os
from smart_heating_local.config import Config

class ConfigTestCase(unittest.TestCase):

    TEMP_DIR = 'temp'
    CONFIG_PATH = TEMP_DIR + '/test_config'

    def setUp(self):
        # Create temporary directory for config files
        if not os.path.exists(self.TEMP_DIR):
            os.mkdir(self.TEMP_DIR)
        Config.CONFIG_PATH = self.CONFIG_PATH

    def tearDown(self):
        # Remove shelve files generated by config
        shutil.rmtree(self.TEMP_DIR)

    def test_thermostat_macs(self):
        macs = ['22:22:22:22:33:33:33:33', '11:11:11:11:44:44:44:44']
        Config().save_thermostat_macs(macs)

        self.assertEqual(macs, Config().get_thermostat_macs())

    def test_heating_table(self):
        mac = '22:22:22:22:33:33:33:33'
        heating_table_entries = [{'id': 1, 'url': 'dummy'},
                          {'id': 2, 'url': 'stub'}]

        Config().save_heating_table(mac, heating_table_entries)

        self.assertEqual(heating_table_entries, Config().get_heating_table(mac))
